# ============================================================================
# CyPerf Agent Client - K8s Pod Deployment
# ============================================================================
# Deploys CyPerf client agent as a pod in cyperf namespace.
# Uses pod networking (no raw sockets) - avoids ENA/PACKET_MMAP issues.
#
# The client connects to the CyPerf Controller via management network,
# then sends test traffic through nginx pods where CloudLens captures it.
#
# Image: templated via ${CYPERF_AGENT_IMAGE} - substituted by deploy-cyperf-k8s.sh
# Ref: https://github.com/Keysight/cyperf/tree/main/deployment/k8s
# ============================================================================
---
apiVersion: v1
kind: Pod
metadata:
  name: cyperf-agent-client
  namespace: cyperf
  labels:
    app: cyperf-agent
    role: client
spec:
  containers:
  - name: cyperf-agent
    image: ${CYPERF_AGENT_IMAGE}
    env:
    - name: AGENT_CONTROLLER
      value: "${CONTROLLER_PRIVATE_IP}"
    - name: AGENT_TAGS
      value: "role=client"
    securityContext:
      privileged: false
      capabilities:
        add:
        - NET_ADMIN
        - IPC_LOCK
        - NET_RAW
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
