# ============================================================================
# CyPerf Agent Server - K8s Pod Deployment
# ============================================================================
# Deploys CyPerf server agent as a pod in cyperf namespace.
# Uses pod networking (no raw sockets) - avoids ENA/PACKET_MMAP issues.
#
# The server receives test traffic from the client through nginx pods.
# A ClusterIP Service exposes the server pod for nginx reverse proxy.
#
# Image: public.ecr.aws/keysight/cyperf-agent:release7.0
# Ref: https://github.com/Keysight/cyperf/tree/main/deployment/k8s
# ============================================================================
---
apiVersion: v1
kind: Pod
metadata:
  name: cyperf-agent-server
  namespace: cyperf
  labels:
    app: cyperf-agent
    role: server
spec:
  containers:
  - name: cyperf-agent
    image: public.ecr.aws/keysight/cyperf-agent:release7.0
    env:
    - name: AGENT_CONTROLLER
      value: "${CONTROLLER_PRIVATE_IP}"
    - name: AGENT_TAGS
      value: "role=server"
    securityContext:
      privileged: false
      capabilities:
        add:
        - NET_ADMIN
        - IPC_LOCK
        - NET_RAW
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 2Gi
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: cyperf-agent-server
  namespace: cyperf
  labels:
    app: cyperf-agent
    role: server
spec:
  type: ClusterIP
  selector:
    app: cyperf-agent
    role: server
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
