apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  # Replace with your own base64-encoded TLS certificate and key
  # Generate a self-signed cert: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=nginx"
  # Then base64 encode: cat tls.crt | base64 | tr -d '\n'
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>
